# Generated by Django 5.2.1 on 2025-06-01 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام تسک')),
                ('description', models.TextField(verbose_name='توضیحات تسک')),
                ('priority', models.CharField(choices=[('مهمه برام', 'مهمه برام'), ('حسش بود انجام میدم', 'حسش بود انجام میدم'), ('حسش فعلا نیس', 'حسش فعلا نیس')], default='حسش بود انجام میدم', max_length=50, verbose_name='اولویت تسک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد تسک')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین ویرایش تسک')),
                ('is_completed', models.BooleanField(default=False, verbose_name='آیا تسک انجام شده است؟')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todolists', to=settings.AUTH_USER_MODEL, verbose_name='کاربر صاحب تسک')),
            ],
            options={
                'verbose_name': 'تسک',
                'verbose_name_plural': 'تسک\u200cها',
            },
        ),
    ]
